// Généré par scripts/build-noun-adjectives.mjs — ne pas éditer à la main.
//
// « Quel adjectif peut qualifier ce nom », replié depuis les 270 contextes
// écrits à la main de lib/adjectives. Aucune paire n'est inventée : chacune
// vient d'une phrase relue. C'est cette relation qui manquait au module Cas
// pour composer un groupe nominal sans retomber dans l'à-peu-près qui l'en
// avait fait sortir — voir l'en-tête du script.
//
// 86 noms, 127 couples.

export const NOUN_ADJECTIVES: Record<string, string[]> = {
  "advokat": ["khoroshiy"],
  "aktrisa": ["molodoy"],
  "avtor": ["interesnyy"],
  "babushka": ["khoroshiy"],
  "blyudo": ["vkusnyy"],
  "braslet": ["krasivyy"],
  "brat": ["novyy"],
  "chelovek": ["umnyy"],
  "chemodan": ["bolshoy", "siniy"],
  "dedushka": ["staryy"],
  "den": ["khoroshiy"],
  "derevo": ["staryy"],
  "devochka": ["umnyy"],
  "dom": ["novyy", "staryy"],
  "drug": ["dorogoy", "khoroshiy", "staryy"],
  "film": ["interesnyy"],
  "fotografiya": ["staryy"],
  "galstuk": ["yarkiy"],
  "geniy": ["yarkiy"],
  "geroy": ["russkiy"],
  "gorod": ["bolshoy", "krasivyy"],
  "gost": ["interesnyy"],
  "istoriya": ["interesnyy"],
  "kartina": ["krasivyy"],
  "khleb": ["khoroshiy"],
  "kholodilnik": ["novyy"],
  "khudozhnik": ["yarkiy"],
  "kniga": ["interesnyy", "novyy", "russkiy", "siniy", "staryy"],
  "koltso": ["dorogoy", "krasivyy"],
  "kompyuter": ["novyy"],
  "korol": ["molodoy", "russkiy"],
  "koroleva": ["molodoy", "staryy"],
  "koshka": ["malenkiy", "umnyy"],
  "kot": ["krasivyy"],
  "leto": ["tyoplyy"],
  "magazin": ["novyy"],
  "mashina": ["krasivyy"],
  "menedzher": ["novyy"],
  "mesto": ["khoroshiy"],
  "most": ["krasivyy", "staryy"],
  "muzh": ["khoroshiy"],
  "muzhchina": ["khoroshiy", "molodoy"],
  "nachalnik": ["russkiy"],
  "napitok": ["kholodnyy"],
  "nevesta": ["krasivyy"],
  "noch": ["kholodnyy"],
  "nozh": ["bolshoy", "russkiy"],
  "odezhda": ["tyoplyy"],
  "ofitser": ["molodoy", "russkiy"],
  "okno": ["bolshoy", "malenkiy", "novyy"],
  "otets": ["dorogoy", "khoroshiy"],
  "pidzhak": ["tyoplyy"],
  "pilot": ["molodoy"],
  "pirog": ["vkusnyy", "yarkiy"],
  "pisatel": ["molodoy", "russkiy"],
  "pismo": ["staryy"],
  "plate": ["krasivyy", "novyy", "siniy", "yarkiy"],
  "podarok": ["dorogoy"],
  "prestupnik": ["plokhoy"],
  "rabota": ["domashniy", "interesnyy"],
  "rebyonok": ["malenkiy"],
  "restoran": ["dorogoy"],
  "sad": ["molodoy"],
  "shpion": ["staryy"],
  "sobaka": ["bolshoy", "malenkiy"],
  "sosed": ["khoroshiy", "novyy", "plokhoy", "umnyy"],
  "stol": ["malenkiy", "novyy", "staryy"],
  "strana": ["tyoplyy"],
  "student": ["khoroshiy", "novyy", "umnyy"],
  "stul": ["novyy"],
  "sup": ["vkusnyy"],
  "syr": ["khoroshiy", "vkusnyy"],
  "telefon": ["novyy"],
  "tort": ["vkusnyy"],
  "tovarishch": ["russkiy"],
  "tsvetok": ["krasivyy", "yarkiy"],
  "uchitel": ["khoroshiy", "molodoy", "novyy"],
  "vino": ["khoroshiy", "tyoplyy"],
  "volk": ["plokhoy"],
  "vrach": ["khoroshiy", "molodoy"],
  "yabloko": ["vkusnyy"],
  "yazyk": ["russkiy"],
  "zerkalo": ["dorogoy"],
  "zhenshchina": ["molodoy", "yarkiy"],
  "zhurnal": ["interesnyy"],
  "zima": ["kholodnyy"],
};
